export const EXTERNAL_LINKS = {
  faucet: 'https://faucet.xone.plus/',
  docs: 'https://docs.xone.plus/',
  TestnetExplorer: 'https://testnet.xscscan.com/',
  Events: 'https://lu.ma/xone',
  Github: 'https://github.com/huione-labs',
  Twitter: 'https://x.com/xone_chain',
  Telegram: 'https://t.me/Xone_Group',
  Youtube: 'https://www.youtube.com/@HelloXone',
  Medium: 'https://medium.com/@xone_chain',
  Donate: 'https://knight.center/',
  DonateDocs: 'https://docs.knight.center/',
  Bridge: 'https://bridge.xonetest.plus/',
  TokenUp:'https://tokenup.xonetest.plus/',
  SwapX:'https://swapx.xonetest.plus/zh',
  RainLink:'https://bridge.xonetest.plus/',
  Discord: 'https://discord.gg/TykpCEbY',
};
