export const EXTERNAL_LINKS = {
  faucet: "https://faucet.xone.org/en",
  docs: "https://docs.xone.org/",
  dashboard: "https://bvi.xone.org/",
  TestnetExplorer: "https://testnet.xscscan.com",
  MainExplorer: "https://xonescan.com/",
  Events: "https://lu.ma/xone",
  Github: "https://github.com/hello-xone/",
  Twitter: "https://x.com/xone_chain",
  Telegram: "https://t.me/hello_xonechain",
  TelegramDevelopers: "https://t.me/Xone_Developers",
  Youtube: "https://www.youtube.com/@HelloXone",
  Medium: "https://medium.com/@xone_chain",
  Donate: "https://knight.center/",
  DonateDocs: "https://docs.knight.center/",
  Bridge: "https://rainlink.co",
  TokenUp: "https://tokenup.org/en",
  SwapX: "https://swapx.exchange/en",
  RainLink: "https://rainlink.co",
  ChatMe: "https://share.chatme.global/share/group/ztgqmws2k?lang=en&mode=light",
  Discord: "https://discord.com/invite/Du9y2GHV",
  Reddit: "https://www.reddit.com/r/XoneChain/",
  Official_Email: "hello@xone.org",
  Support_Email: "support@xone.org",
  Business_Email: "business@xone.org",
  Newsletter_Email: "newsletter@xone.org",
  Developers_Email: "developers@xone.org",
  Work_Email: "job@xone.org",
  Community_Email: "community@xone.org",
  Suggest_Dapp:
    "https://github.com/hello-xone/official_docs/issues/new?template=suggest_dapp.yaml",
  Bvi: "https://bvi.xone.org/zh-CN/ecology",
};
